[package]
name = "litra"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
exitcode = "1.1.2"
hidapi = "2.4.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"